version: '3.3'

services:

  db:
    image: mysql:8
    container_name: perfect_wedding_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: perfect_wedding
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3310:3310"
    networks:
      - backend

volumes:
  db_data:

networks:
  backend: